name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Inicia sesiÃ³n en Docker Hub con el token
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Tu nombre de usuario de Docker Hub
        password: ${{ secrets.DOCKER_HUB_TOKEN }}  # El token generado previamente

    # Construir la imagen de Docker y generar un tag
    - name: Build the Docker image
      id: build
      run: |
        IMAGE_TAG=gonzat/repogithub:$(date +%s)  # Usa tu nombre de usuario en lugar de 'mi-usuario'
        docker build . --file Dockerfile --tag $IMAGE_TAG  # Etiquetar la imagen con el tag
        echo "Built image with tag: $IMAGE_TAG"  # Mostrar el tag de la imagen construida
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV  # Guardar el tag en el ambiente global

    # Empujar la imagen al Docker Hub
    - name: Push the Docker image
      run: |
        docker push $IMAGE_TAG  # Usar el tag previamente guardado en el ambiente global
